#############################################################################
# Makefile for building: wallch
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon Sep 5 14:57:03 2011
# Project:  wallch.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile wallch.pro
#############################################################################

####### Compiler, tools and options

CC            = /usr/bin/gcc
CXX           = /usr/bin/g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -g3 -gdwarf-2 -O2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libnotifymm-1.0 -I/usr/lib/libnotifymm-1.0/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pixman-1 -pthread -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gio-unix-2.0/ -I/usr/include/gtkmm-2.4 -I/usr/lib/gtkmm-2.4/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/pangomm-1.4/include -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gdkmm-2.4 -I/usr/lib/gdkmm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/cairomm-1.0 -I/usr/lib/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/lib/gtk-2.0/include -I/usr/include/gdk-pixbuf-2.0 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -g3 -gdwarf-2 -O2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libnotifymm-1.0 -I/usr/lib/libnotifymm-1.0/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pixman-1 -pthread -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gio-unix-2.0/ -I/usr/include/gtkmm-2.4 -I/usr/lib/gtkmm-2.4/include -I/usr/include/atkmm-1.6 -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/pangomm-1.4/include -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gdkmm-2.4 -I/usr/lib/gdkmm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/cairomm-1.0 -I/usr/lib/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/lib/gtk-2.0/include -I/usr/include/gdk-pixbuf-2.0 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/phonon -I/usr/include/qt4 -I/usr/include -I/usr/include -I/usr/include -I/usr/include/qt4/phonon_compat -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lcv -lhighgui -L/home/maxmahem/wallch-2.0/../../../usr/lib/ -lgconf-2 -lsfml-audio -L/usr/lib/x86_64-linux-gnu -lnotifymm-1.0 -lnotify -ldbus-glib-1 -ldbus-1 -pthread -lgtkmm-2.4 -latkmm-1.6 -lgdkmm-2.4 -lgiomm-2.4 -lpangomm-1.4 -lgtk-x11-2.0 -lglibmm-2.4 -lcairomm-1.0 -lsigc-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lm -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lphonon -lQtDBus -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = about.cpp \
		main.cpp \
		mainwindow.cpp \
		preferences.cpp \
		properties.cpp moc_about.cpp \
		moc_mainwindow.cpp \
		moc_preferences.cpp \
		moc_properties.cpp \
		qrc_icons.cpp
OBJECTS       = about.o \
		main.o \
		mainwindow.o \
		preferences.o \
		properties.o \
		moc_about.o \
		moc_mainwindow.o \
		moc_preferences.o \
		moc_properties.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		wallch.pro
QMAKE_TARGET  = wallch
DESTDIR       = 
TARGET        = wallch

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/maxmahem/wallch-2.0/../../../usr/lib/libgconf-2.a ui_about.h ui_mainwindow.h ui_preferences.h ui_properties.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wallch.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile wallch.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ QMAKE_CC=/usr/bin/gcc QMAKE_CXX=/usr/bin/g++ QMAKE_CFLAGS=-g3\ -gdwarf-2 QMAKE_CXXFLAGS=-g3\ -gdwarf-2 QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile wallch.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/wallch1.0.0 || $(MKDIR) .tmp/wallch1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/wallch1.0.0/ && $(COPY_FILE) --parents about.h mainwindow.h preferences.h properties.h .tmp/wallch1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/wallch1.0.0/ && $(COPY_FILE) --parents about.cpp main.cpp mainwindow.cpp preferences.cpp properties.cpp .tmp/wallch1.0.0/ && $(COPY_FILE) --parents about.ui mainwindow.ui preferences.ui properties.ui .tmp/wallch1.0.0/ && (cd `dirname .tmp/wallch1.0.0` && $(TAR) wallch1.0.0.tar wallch1.0.0 && $(COMPRESS) wallch1.0.0.tar) && $(MOVE) `dirname .tmp/wallch1.0.0`/wallch1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/wallch1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_about.cpp moc_mainwindow.cpp moc_preferences.cpp moc_properties.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_about.cpp moc_mainwindow.cpp moc_preferences.cpp moc_properties.cpp
moc_about.cpp: about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) about.h -o moc_about.cpp

moc_mainwindow.cpp: about.h \
		ui_mainwindow.h \
		properties.h \
		preferences.h \
		/usr/include/gconf/gconf-client.h \
		/usr/include/gconf/gconf.h \
		/usr/include/gconf/gconf-schema.h \
		/usr/include/gconf/gconf-value.h \
		/usr/include/gconf/gconf-error.h \
		/usr/include/gconf/gconf-engine.h \
		/usr/include/gconf/gconf-enum-types.h \
		/usr/include/gconf/gconf-listeners.h \
		/usr/include/gconf/gconf-changeset.h \
		/usr/include/SFML/Audio.hpp \
		/usr/include/SFML/System.hpp \
		/usr/include/SFML/Config.hpp \
		/usr/include/SFML/System/Clock.hpp \
		/usr/include/SFML/System/Lock.hpp \
		/usr/include/SFML/System/NonCopyable.hpp \
		/usr/include/SFML/System/Mutex.hpp \
		/usr/include/SFML/System/Win32/Mutex.hpp \
		/usr/include/SFML/System/Unix/Mutex.hpp \
		/usr/include/pthread.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sched.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/SFML/System/Randomizer.hpp \
		/usr/include/SFML/System/Sleep.hpp \
		/usr/include/SFML/System/Thread.hpp \
		/usr/include/SFML/System/Win32/Thread.hpp \
		/usr/include/SFML/System/Unix/Thread.hpp \
		/usr/include/SFML/System/Unicode.hpp \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/SFML/System/Unicode.inl \
		/usr/include/SFML/System/Vector2.hpp \
		/usr/include/SFML/System/Vector2.inl \
		/usr/include/SFML/System/Vector3.hpp \
		/usr/include/SFML/System/Vector3.inl \
		/usr/include/SFML/Audio/Listener.hpp \
		/usr/include/SFML/Audio/Music.hpp \
		/usr/include/SFML/Audio/SoundStream.hpp \
		/usr/include/SFML/Audio/Sound.hpp \
		/usr/include/SFML/System/Resource.hpp \
		/usr/include/SFML/System/Resource.inl \
		/usr/include/SFML/System/ResourcePtr.inl \
		/usr/include/SFML/Audio/AudioResource.hpp \
		/usr/include/SFML/Audio/SoundBuffer.hpp \
		/usr/include/SFML/Audio/SoundBufferRecorder.hpp \
		/usr/include/SFML/Audio/SoundRecorder.hpp \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_preferences.cpp: /usr/include/gconf/gconf-client.h \
		/usr/include/gconf/gconf.h \
		/usr/include/gconf/gconf-schema.h \
		/usr/include/gconf/gconf-value.h \
		/usr/include/gconf/gconf-error.h \
		/usr/include/gconf/gconf-engine.h \
		/usr/include/gconf/gconf-enum-types.h \
		/usr/include/gconf/gconf-listeners.h \
		/usr/include/gconf/gconf-changeset.h \
		/usr/include/SFML/Audio.hpp \
		/usr/include/SFML/System.hpp \
		/usr/include/SFML/Config.hpp \
		/usr/include/SFML/System/Clock.hpp \
		/usr/include/SFML/System/Lock.hpp \
		/usr/include/SFML/System/NonCopyable.hpp \
		/usr/include/SFML/System/Mutex.hpp \
		/usr/include/SFML/System/Win32/Mutex.hpp \
		/usr/include/SFML/System/Unix/Mutex.hpp \
		/usr/include/pthread.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sched.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/SFML/System/Randomizer.hpp \
		/usr/include/SFML/System/Sleep.hpp \
		/usr/include/SFML/System/Thread.hpp \
		/usr/include/SFML/System/Win32/Thread.hpp \
		/usr/include/SFML/System/Unix/Thread.hpp \
		/usr/include/SFML/System/Unicode.hpp \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/SFML/System/Unicode.inl \
		/usr/include/SFML/System/Vector2.hpp \
		/usr/include/SFML/System/Vector2.inl \
		/usr/include/SFML/System/Vector3.hpp \
		/usr/include/SFML/System/Vector3.inl \
		/usr/include/SFML/Audio/Listener.hpp \
		/usr/include/SFML/Audio/Music.hpp \
		/usr/include/SFML/Audio/SoundStream.hpp \
		/usr/include/SFML/Audio/Sound.hpp \
		/usr/include/SFML/System/Resource.hpp \
		/usr/include/SFML/System/Resource.inl \
		/usr/include/SFML/System/ResourcePtr.inl \
		/usr/include/SFML/Audio/AudioResource.hpp \
		/usr/include/SFML/Audio/SoundBuffer.hpp \
		/usr/include/SFML/Audio/SoundBufferRecorder.hpp \
		/usr/include/SFML/Audio/SoundRecorder.hpp \
		preferences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) preferences.h -o moc_preferences.cpp

moc_properties.cpp: properties.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) properties.h -o moc_properties.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		data/to_usr_share/wallch/files/notification.ogg \
		Pictures/jpeg_image.png \
		Pictures/world_sunlight_map_rectangular_small.jpg \
		Pictures/gif_image.png \
		Pictures/earth.png \
		Pictures/bmp_image.png \
		Pictures/png_image.png \
		Pictures/speakerL.png \
		Pictures/screen.png \
		Pictures/wallch.png \
		Pictures/world_sunlight_map_hemisphere_small.jpg \
		Pictures/speakerR.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_about.h ui_mainwindow.h ui_preferences.h ui_properties.h
compiler_uic_clean:
	-$(DEL_FILE) ui_about.h ui_mainwindow.h ui_preferences.h ui_properties.h
ui_about.h: about.ui
	/usr/bin/uic-qt4 about.ui -o ui_about.h

ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_preferences.h: preferences.ui
	/usr/bin/uic-qt4 preferences.ui -o ui_preferences.h

ui_properties.h: properties.ui
	/usr/bin/uic-qt4 properties.ui -o ui_properties.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

about.o: about.cpp about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

main.o: main.cpp mainwindow.h \
		about.h \
		ui_mainwindow.h \
		properties.h \
		preferences.h \
		/usr/include/gconf/gconf-client.h \
		/usr/include/gconf/gconf.h \
		/usr/include/gconf/gconf-schema.h \
		/usr/include/gconf/gconf-value.h \
		/usr/include/gconf/gconf-error.h \
		/usr/include/gconf/gconf-engine.h \
		/usr/include/gconf/gconf-enum-types.h \
		/usr/include/gconf/gconf-listeners.h \
		/usr/include/gconf/gconf-changeset.h \
		/usr/include/SFML/Audio.hpp \
		/usr/include/SFML/System.hpp \
		/usr/include/SFML/Config.hpp \
		/usr/include/SFML/System/Clock.hpp \
		/usr/include/SFML/System/Lock.hpp \
		/usr/include/SFML/System/NonCopyable.hpp \
		/usr/include/SFML/System/Mutex.hpp \
		/usr/include/SFML/System/Win32/Mutex.hpp \
		/usr/include/SFML/System/Unix/Mutex.hpp \
		/usr/include/pthread.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sched.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/SFML/System/Randomizer.hpp \
		/usr/include/SFML/System/Sleep.hpp \
		/usr/include/SFML/System/Thread.hpp \
		/usr/include/SFML/System/Win32/Thread.hpp \
		/usr/include/SFML/System/Unix/Thread.hpp \
		/usr/include/SFML/System/Unicode.hpp \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/SFML/System/Unicode.inl \
		/usr/include/SFML/System/Vector2.hpp \
		/usr/include/SFML/System/Vector2.inl \
		/usr/include/SFML/System/Vector3.hpp \
		/usr/include/SFML/System/Vector3.inl \
		/usr/include/SFML/Audio/Listener.hpp \
		/usr/include/SFML/Audio/Music.hpp \
		/usr/include/SFML/Audio/SoundStream.hpp \
		/usr/include/SFML/Audio/Sound.hpp \
		/usr/include/SFML/System/Resource.hpp \
		/usr/include/SFML/System/Resource.inl \
		/usr/include/SFML/System/ResourcePtr.inl \
		/usr/include/SFML/Audio/AudioResource.hpp \
		/usr/include/SFML/Audio/SoundBuffer.hpp \
		/usr/include/SFML/Audio/SoundBufferRecorder.hpp \
		/usr/include/SFML/Audio/SoundRecorder.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		about.h \
		ui_mainwindow.h \
		properties.h \
		preferences.h \
		/usr/include/gconf/gconf-client.h \
		/usr/include/gconf/gconf.h \
		/usr/include/gconf/gconf-schema.h \
		/usr/include/gconf/gconf-value.h \
		/usr/include/gconf/gconf-error.h \
		/usr/include/gconf/gconf-engine.h \
		/usr/include/gconf/gconf-enum-types.h \
		/usr/include/gconf/gconf-listeners.h \
		/usr/include/gconf/gconf-changeset.h \
		/usr/include/SFML/Audio.hpp \
		/usr/include/SFML/System.hpp \
		/usr/include/SFML/Config.hpp \
		/usr/include/SFML/System/Clock.hpp \
		/usr/include/SFML/System/Lock.hpp \
		/usr/include/SFML/System/NonCopyable.hpp \
		/usr/include/SFML/System/Mutex.hpp \
		/usr/include/SFML/System/Win32/Mutex.hpp \
		/usr/include/SFML/System/Unix/Mutex.hpp \
		/usr/include/pthread.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sched.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/SFML/System/Randomizer.hpp \
		/usr/include/SFML/System/Sleep.hpp \
		/usr/include/SFML/System/Thread.hpp \
		/usr/include/SFML/System/Win32/Thread.hpp \
		/usr/include/SFML/System/Unix/Thread.hpp \
		/usr/include/SFML/System/Unicode.hpp \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/SFML/System/Unicode.inl \
		/usr/include/SFML/System/Vector2.hpp \
		/usr/include/SFML/System/Vector2.inl \
		/usr/include/SFML/System/Vector3.hpp \
		/usr/include/SFML/System/Vector3.inl \
		/usr/include/SFML/Audio/Listener.hpp \
		/usr/include/SFML/Audio/Music.hpp \
		/usr/include/SFML/Audio/SoundStream.hpp \
		/usr/include/SFML/Audio/Sound.hpp \
		/usr/include/SFML/System/Resource.hpp \
		/usr/include/SFML/System/Resource.inl \
		/usr/include/SFML/System/ResourcePtr.inl \
		/usr/include/SFML/Audio/AudioResource.hpp \
		/usr/include/SFML/Audio/SoundBuffer.hpp \
		/usr/include/SFML/Audio/SoundBufferRecorder.hpp \
		/usr/include/SFML/Audio/SoundRecorder.hpp \
		/usr/include/sys/stat.h \
		/usr/include/bits/stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

preferences.o: preferences.cpp preferences.h \
		/usr/include/gconf/gconf-client.h \
		/usr/include/gconf/gconf.h \
		/usr/include/gconf/gconf-schema.h \
		/usr/include/gconf/gconf-value.h \
		/usr/include/gconf/gconf-error.h \
		/usr/include/gconf/gconf-engine.h \
		/usr/include/gconf/gconf-enum-types.h \
		/usr/include/gconf/gconf-listeners.h \
		/usr/include/gconf/gconf-changeset.h \
		/usr/include/SFML/Audio.hpp \
		/usr/include/SFML/System.hpp \
		/usr/include/SFML/Config.hpp \
		/usr/include/SFML/System/Clock.hpp \
		/usr/include/SFML/System/Lock.hpp \
		/usr/include/SFML/System/NonCopyable.hpp \
		/usr/include/SFML/System/Mutex.hpp \
		/usr/include/SFML/System/Win32/Mutex.hpp \
		/usr/include/SFML/System/Unix/Mutex.hpp \
		/usr/include/pthread.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/sys/cdefs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/sched.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/SFML/System/Randomizer.hpp \
		/usr/include/SFML/System/Sleep.hpp \
		/usr/include/SFML/System/Thread.hpp \
		/usr/include/SFML/System/Win32/Thread.hpp \
		/usr/include/SFML/System/Unix/Thread.hpp \
		/usr/include/SFML/System/Unicode.hpp \
		/usr/include/stdlib.h \
		/usr/include/bits/waitflags.h \
		/usr/include/bits/waitstatus.h \
		/usr/include/sys/types.h \
		/usr/include/sys/select.h \
		/usr/include/bits/select.h \
		/usr/include/bits/sigset.h \
		/usr/include/sys/sysmacros.h \
		/usr/include/alloca.h \
		/usr/include/bits/stdlib.h \
		/usr/include/bits/stdlib-ldbl.h \
		/usr/include/SFML/System/Unicode.inl \
		/usr/include/SFML/System/Vector2.hpp \
		/usr/include/SFML/System/Vector2.inl \
		/usr/include/SFML/System/Vector3.hpp \
		/usr/include/SFML/System/Vector3.inl \
		/usr/include/SFML/Audio/Listener.hpp \
		/usr/include/SFML/Audio/Music.hpp \
		/usr/include/SFML/Audio/SoundStream.hpp \
		/usr/include/SFML/Audio/Sound.hpp \
		/usr/include/SFML/System/Resource.hpp \
		/usr/include/SFML/System/Resource.inl \
		/usr/include/SFML/System/ResourcePtr.inl \
		/usr/include/SFML/Audio/AudioResource.hpp \
		/usr/include/SFML/Audio/SoundBuffer.hpp \
		/usr/include/SFML/Audio/SoundBufferRecorder.hpp \
		/usr/include/SFML/Audio/SoundRecorder.hpp \
		ui_preferences.h \
		/usr/include/glob.h \
		/usr/include/sys/stat.h \
		/usr/include/bits/stat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o preferences.cpp

properties.o: properties.cpp properties.h \
		ui_properties.h \
		/usr/include/glob.h \
		/usr/include/sys/cdefs.h \
		/usr/include/features.h \
		/usr/include/bits/predefs.h \
		/usr/include/gnu/stubs.h \
		/usr/include/bits/wordsize.h \
		/usr/include/gnu/stubs-64.h \
		/usr/include/sys/stat.h \
		/usr/include/bits/types.h \
		/usr/include/bits/typesizes.h \
		/usr/include/time.h \
		/usr/include/bits/time.h \
		/usr/include/xlocale.h \
		/usr/include/bits/stat.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/bits/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/bits/endian.h \
		/usr/include/bits/byteswap.h \
		/usr/include/bits/wchar2.h \
		/usr/include/bits/wchar-ldbl.h \
		/usr/include/gconv.h \
		/usr/include/bits/stdio-lock.h \
		/usr/include/bits/libc-lock.h \
		/usr/include/pthread.h \
		/usr/include/sched.h \
		/usr/include/bits/sched.h \
		/usr/include/bits/pthreadtypes.h \
		/usr/include/bits/setjmp.h \
		/usr/include/errno.h \
		/usr/include/bits/errno.h \
		/usr/include/linux/errno.h \
		/usr/include/gnu/option-groups.h \
		/usr/include/bits/libio-ldbl.h \
		/usr/include/bits/stdio_lim.h \
		/usr/include/bits/sys_errlist.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/bits/stdio.h \
		/usr/include/bits/stdio2.h \
		/usr/include/bits/stdio-ldbl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o properties.o properties.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_properties.o: moc_properties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_properties.o moc_properties.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install_configfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/ 
	make clean; update-desktop-database;
	-$(INSTALL_DIR) /home/maxmahem/wallch-2.0/data/to_usr_share/wallch $(INSTALL_ROOT)/usr/share/


uninstall_configfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/wallch
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/ 


install_shortcutfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/maxmahem/wallch-2.0/data/wallch.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_shortcutfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/wallch.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_helpfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/gnome/help/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/gnome/help/ 
	-$(INSTALL_DIR) /home/maxmahem/wallch-2.0/data/help/wallch $(INSTALL_ROOT)/usr/share/gnome/help/


uninstall_helpfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/gnome/help/wallch
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/gnome/help/ 


install_binfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) /home/maxmahem/wallch-2.0/wallch $(INSTALL_ROOT)/usr/bin/
	-strip $(INSTALL_ROOT)/usr/bin/wallch


uninstall_binfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/bin/wallch
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_manfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/man/man2/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/man/man2/ 
	-$(INSTALL_FILE) /home/maxmahem/wallch-2.0/data/man/wallch.2.gz $(INSTALL_ROOT)/usr/share/man/man2/


uninstall_manfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/man/man2/wallch.2.gz
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/man/man2/ 


install_docfiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/doc/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/doc/ 
	mkdir -p /usr/share/icons/hicolor/128x128/mimetypes/; mkdir -p /usr/share/icons/hicolor/64x64/mimetypes/; mkdir -p /usr/share/icons/hicolor/48x48/mimetypes/; mkdir -p /usr/share/icons/hicolor/32x32/mimetypes/; mkdir -p /usr/share/icons/hicolor/22x22/mimetypes/; mkdir -p /usr/share/icons/hicolor/1616/mimetypes/; mkdir -p /etc/wallch/translations/
	-$(INSTALL_FILE) /home/maxmahem/wallch-2.0/data/doc/wallch/copyright $(INSTALL_ROOT)/usr/share/doc/
	-$(INSTALL_DIR) /home/maxmahem/wallch-2.0/data/doc/wallch $(INSTALL_ROOT)/usr/share/doc/


uninstall_docfiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/copyright 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/wallch
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/ 


install_imagefiles: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/pixmaps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 
	cp data/mime/128/application-x-wallch-project.png /usr/share/icons/hicolor/128x128/mimetypes/; cp data/mime/64/application-x-wallch-project.png /usr/share/icons/hicolor/64x64/mimetypes/; cp data/mime/48/application-x-wallch-project.png /usr/share/icons/hicolor/48x48/mimetypes/; cp data/mime/32/application-x-wallch-project.png /usr/share/icons/hicolor/32x32/mimetypes/; cp data/mime/22/application-x-wallch-project.png /usr/share/icons/hicolor/22x22/mimetypes/; cp data/mime/16/application-x-wallch-project.png /usr/share/icons/hicolor/16x16/mimetypes/; cp data/mime/wallch.xml /usr/share/mime/packages/; cp data/translations/wallch_gr.qm /etc/wallch/translations/
	-$(INSTALL_FILE) /home/maxmahem/wallch-2.0/data/pixmap/wallch.png $(INSTALL_ROOT)/usr/share/pixmaps/


uninstall_imagefiles:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/wallch.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install:  install_configfiles install_shortcutfiles install_helpfiles install_binfiles install_manfiles install_docfiles install_imagefiles  FORCE

uninstall: uninstall_configfiles uninstall_shortcutfiles uninstall_helpfiles uninstall_binfiles uninstall_manfiles uninstall_docfiles uninstall_imagefiles   FORCE

FORCE:

