.TH "/home/maxmahem/wallch-2.0/about.cpp" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/about.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'about.h'\fP
.br
\fC#include 'ui_about.h'\fP
.br
\fC#include 'iostream'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
