.TH "Extras" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extras \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <extras.h>\fP
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstart_live_earth\fP ()"
.br
.ti -1c
.RI "void \fBstop_live_earth\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtras\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Extras\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file extras.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Extras::Extras (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 33 of file extras.cpp.
.SS "Extras::~Extras ()"
.PP
Definition at line 66 of file extras.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Extras::start_live_earth ()\fC [signal]\fP"
.PP
Definition at line 111 of file moc_extras.cpp.
.SS "void Extras::stop_live_earth ()\fC [signal]\fP"
.PP
Definition at line 117 of file moc_extras.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
