.TH "/home/maxmahem/wallch-2.0/extras.cpp" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/extras.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'extras.h'\fP
.br
\fC#include 'ui_extras.h'\fP
.br
\fC#include 'glob.h'\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
