.TH "/home/maxmahem/wallch-2.0/mainwindow.h" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'about.h'\fP
.br
\fC#include 'ui_mainwindow.h'\fP
.br
\fC#include 'properties.h'\fP
.br
\fC#include 'preferences.h'\fP
.br
\fC#include 'extras.h'\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QSystemTrayIcon>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QDragEnterEvent>\fP
.br
\fC#include <QDropEvent>\fP
.br
\fC#include <QtNetwork>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
