.TH "/home/maxmahem/wallch-2.0/moc_properties.cpp" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/moc_properties.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'properties.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__pad0__\fP"
.br
.ti -1c
.RI "\fB__pad1__\fP"
.br
.ti -1c
.RI "int \fB_id\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "__pad0__"
.PP
Definition at line 44 of file moc_properties.cpp.
.SS "__pad1__"
.PP
Definition at line 65 of file moc_properties.cpp.
.SS "int _id"
.PP
Definition at line 65 of file moc_properties.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
