.TH "/home/maxmahem/wallch-2.0/preferences.h" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/preferences.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <gconf/gconf-client.h>\fP
.br
\fC#include <SFML/Audio.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPreferences\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEFAULTSOUNDFILE\fP   '/usr/share/wallch/files/notification.ogg';"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DEFAULTSOUNDFILE   '/usr/share/wallch/files/notification.ogg';"
.PP
Definition at line 29 of file preferences.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
