.TH "Preferences" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Preferences \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <preferences.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBstartupEnum\fP { \fBrun\fP, \fBonce\fP, \fBliveEarth\fP }"
.br
.ti -1c
.RI "enum \fBbackgroundSettingEnum\fP { \fBwallpaper\fP, \fBzoom\fP, \fBcentered\fP, \fBscaled\fP, \fBstreched\fP, \fBspanned\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreferences\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Preferences\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file preferences.h.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPreferences::backgroundSettingEnum\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIwallpaper \fP\fP
.TP
\fB\fIzoom \fP\fP
.TP
\fB\fIcentered \fP\fP
.TP
\fB\fIscaled \fP\fP
.TP
\fB\fIstreched \fP\fP
.TP
\fB\fIspanned \fP\fP

.PP
Definition at line 43 of file preferences.h.
.SS "enum \fBPreferences::startupEnum\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIrun \fP\fP
.TP
\fB\fIonce \fP\fP
.TP
\fB\fIliveEarth \fP\fP

.PP
Definition at line 42 of file preferences.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Preferences::Preferences (QWidget *parent = \fC0\fP)"
.PP
Definition at line 39 of file preferences.cpp.
.SS "Preferences::~Preferences ()"
.PP
Definition at line 81 of file preferences.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
