.TH "properties" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
properties \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <properties.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproperties\fP (QString &img, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~properties\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file properties.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "properties::properties (QString &img, QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 36 of file properties.cpp.
.SS "properties::~properties ()"
.PP
Definition at line 76 of file properties.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void properties::resizeEvent (QResizeEvent *event)\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
