.TH "QOpenCVWidget" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QOpenCVWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <QOpenCVWidget.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQOpenCVWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~QOpenCVWidget\fP (void)"
.br
.ti -1c
.RI "void \fBputImage\fP (IplImage *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file QOpenCVWidget.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QOpenCVWidget::QOpenCVWidget (QWidget *parent = \fC0\fP)"
.PP
Definition at line 25 of file QOpenCVWidget.cpp.
.SS "QOpenCVWidget::~QOpenCVWidget (void)"
.PP
Definition at line 41 of file QOpenCVWidget.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void QOpenCVWidget::putImage (IplImage *cvimage)"
.PP
Definition at line 45 of file QOpenCVWidget.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
