.TH "/home/maxmahem/wallch-2.0/QOpenCVWidget.h" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/QOpenCVWidget.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <opencv/cv.h>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QImage>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQOpenCVWidget\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
