.TH "/home/maxmahem/wallch-2.0/qrc_icons.cpp" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/qrc_icons.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qglobal.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool \fBqRegisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "Q_CORE_EXPORT bool \fBqUnregisterResourceData\fP (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.br
.ti -1c
.RI "QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() \fBqInitResources_icons\fP ()"
.br
.ti -1c
.RI "int QT_MANGLE_NAMESPACE() \fBqCleanupResources_icons\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int QT_MANGLE_NAMESPACE() qCleanupResources_icons ()"
.PP
Definition at line 10091 of file qrc_icons.cpp.
.SS "QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_icons ()"
.PP
Definition at line 10082 of file qrc_icons.cpp.
.SS "QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.SS "Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
