.TH "statistics" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statistics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statistics.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatistics\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~statistics\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file statistics.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "statistics::statistics (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.SS "statistics::~statistics ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
