.TH "Ui::about" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::about \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_about.h>\fP
.PP
Inherits \fBUi_about\fP.
.SH "Detailed Description"
.PP 
Definition at line 195 of file ui_about.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
