.TH "Ui::Extras" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::Extras \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_extras.h>\fP
.PP
Inherits \fBUi_Extras\fP.
.SH "Detailed Description"
.PP 
Definition at line 226 of file ui_extras.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
