.TH "Ui::history" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::history \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_history.h>\fP
.PP
Inherits \fBUi_history\fP.
.SH "Detailed Description"
.PP 
Definition at line 81 of file ui_history.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
