.TH "/home/maxmahem/wallch-2.0/ui_history.h" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/ui_history.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QAction>\fP
.br
\fC#include <QtGui/QApplication>\fP
.br
\fC#include <QtGui/QButtonGroup>\fP
.br
\fC#include <QtGui/QDialog>\fP
.br
\fC#include <QtGui/QHeaderView>\fP
.br
\fC#include <QtGui/QListWidget>\fP
.br
\fC#include <QtGui/QPushButton>\fP
.br
\fC#include <QtGui/QTreeWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_history\fP"
.br
.ti -1c
.RI "class \fBUi::history\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
