.TH "Ui::MainWindow" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow.h>\fP
.PP
Inherits \fBUi_MainWindow\fP.
.SH "Detailed Description"
.PP 
Definition at line 417 of file ui_mainwindow.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
