.TH "Ui::properties" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::properties \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_properties.h>\fP
.PP
Inherits \fBUi_properties\fP.
.SH "Detailed Description"
.PP 
Definition at line 172 of file ui_properties.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
