.TH "/home/maxmahem/wallch-2.0/ui_preferences.h" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/maxmahem/wallch-2.0/ui_preferences.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QAction>\fP
.br
\fC#include <QtGui/QApplication>\fP
.br
\fC#include <QtGui/QButtonGroup>\fP
.br
\fC#include <QtGui/QCheckBox>\fP
.br
\fC#include <QtGui/QComboBox>\fP
.br
\fC#include <QtGui/QDialog>\fP
.br
\fC#include <QtGui/QFormLayout>\fP
.br
\fC#include <QtGui/QGroupBox>\fP
.br
\fC#include <QtGui/QHBoxLayout>\fP
.br
\fC#include <QtGui/QHeaderView>\fP
.br
\fC#include <QtGui/QLabel>\fP
.br
\fC#include <QtGui/QPushButton>\fP
.br
\fC#include <QtGui/QRadioButton>\fP
.br
\fC#include <QtGui/QSpacerItem>\fP
.br
\fC#include <QtGui/QTabWidget>\fP
.br
\fC#include <QtGui/QVBoxLayout>\fP
.br
\fC#include <QtGui/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_Preferences\fP"
.br
.ti -1c
.RI "class \fBUi::Preferences\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
