.TH "Ui::screenshot" 3 "Wed Aug 31 2011" "Version 2.1" "Wallch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::screenshot \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_screenshot.h>\fP
.PP
Inherits \fBUi_screenshot\fP.
.SH "Detailed Description"
.PP 
Definition at line 134 of file ui_screenshot.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Wallch from the source code.
