Ui_about
QPushButton* Ui_about::closeButton
Referenced by retranslateUi, setupUi.
QPushButton* Ui_about::pushButton_2
Referenced by retranslateUi, setupUi.
QPushButton* Ui_about::pushButton_3
Referenced by retranslateUi, setupUi.
QPushButton* Ui_about::pushButton
Referenced by retranslateUi, setupUi.
QStackedWidget* Ui_about::stackedWidget
Referenced by setupUi.
QWidget* Ui_about::page
Referenced by setupUi.
QLabel* Ui_about::label
Referenced by retranslateUi, setupUi.
QLabel* Ui_about::label_4
Referenced by about::about, retranslateUi, setupUi.
QLabel* Ui_about::label_3
Referenced by retranslateUi, setupUi.
QLabel* Ui_about::label_2
Referenced by setupUi.
QLabel* Ui_about::label_5
Referenced by about::about, retranslateUi, setupUi.
QLabel* Ui_about::label_6
Referenced by retranslateUi, setupUi.
QWidget* Ui_about::page_2
Referenced by setupUi.
QTabWidget* Ui_about::tabWidget
Referenced by retranslateUi, setupUi.
QWidget* Ui_about::tab
Referenced by retranslateUi, setupUi.
QTextBrowser* Ui_about::textBrowser
Referenced by about::about, setupUi.
QWidget* Ui_about::tab_2
Referenced by retranslateUi, setupUi.
QTextBrowser* Ui_about::textBrowser_2
Referenced by about::about, setupUi.
QWidget* Ui_about::page_3
Referenced by setupUi.
QPlainTextEdit* Ui_about::plain
Referenced by setupUi.
void Ui_about::setupUi(QDialog *about)
References closeButton, label, label_2, label_3, label_4, label_5, label_6, page, page_2, page_3, plain, pushButton, pushButton_2, pushButton_3, retranslateUi, stackedWidget, tab, tab_2, tabWidget, textBrowser, textBrowser_2.
Referenced by about::about.
void Ui_about::retranslateUi(QDialog *about)
References closeButton, label, label_3, label_4, label_5, label_6, pushButton, pushButton_2, pushButton_3, tab, tab_2, tabWidget.
Referenced by about::changeEvent, setupUi.