MainWindow
Ui::MainWindow* MainWindow::ui
QSystemTrayIcon* MainWindow::trayIcon
QTimer* MainWindow::update_time
QTimer* MainWindow::earth_timer
QAction* MainWindow::Start_action
QAction* MainWindow::Stop_action
QAction* MainWindow::Next_action
QAction* MainWindow::Previous_action
QAction* MainWindow::Show_action
QAction* MainWindow::Settings_action
QAction* MainWindow::About_action
QAction* MainWindow::Quit_action
about* MainWindow::About
Preferences* MainWindow::preferences
properties* MainWindow::Properties
Extras* MainWindow::extras
QUrl MainWindow::url
QNetworkAccessManager MainWindow::qnam
QNetworkReply* MainWindow::reply
int MainWindow::delayMinutes
int MainWindow::timerMinutes
bool MainWindow::desktopNotification
bool MainWindow::soundNotification
bool MainWindow::running
MainWindow::MainWindow(QWidget *parent=0)
References Ui_MainWindow::action_About, Ui_MainWindow::action_Load, Ui_MainWindow::action_Next_Image, Ui_MainWindow::action_Preferences, Ui_MainWindow::action_Previous_Image_Shift_Ctrl_B, Ui_MainWindow::action_Start, Ui_MainWindow::actionAdd_a_Wallch_album, Ui_MainWindow::actionAdd_Folder, Ui_MainWindow::actionAdd_single_images, Ui_MainWindow::actionExtras, Ui_MainWindow::actionQuit_Ctrl_Q, Ui_MainWindow::actionRemove_list, Ui_MainWindow::actionS_top, Ui_MainWindow::addButton, Ui_MainWindow::addfolder, clickSysTrayIcon, close_minimize, Ui_MainWindow::listWidget, load, Ui_MainWindow::menuAdd_Files, menushowabout, minimize_to_tray, minimized, Ui_MainWindow::nextButton, Ui_MainWindow::previousButton, pruneList, Ui_MainWindow::removeallButton, Ui_MainWindow::removeButton, save_album, Ui_MainWindow::save_as, Ui_MainWindow::setupUi, showClicked, ShowExtras, ShowPreferences, showProperties, Ui_MainWindow::startButton, Ui_MainWindow::stopButton, Ui_MainWindow::timerSlider.
MainWindow::~MainWindow()
void MainWindow::changeEvent(QEvent *e)
References add, minimize_to_tray, minimized, pref, Ui_MainWindow::retranslateUi.
void MainWindow::closeEvent(QCloseEvent *)
void MainWindow::on_previousButton_clicked()
void MainWindow::on_addfolder_clicked()
void MainWindow::on_listWidget_customContextMenuRequested()
void MainWindow::on_listWidget_itemDoubleClicked()
void MainWindow::on_listWidget_itemSelectionChanged()
void MainWindow::on_removeallButton_clicked()
void MainWindow::on_removeButton_clicked()
void MainWindow::on_addButton_clicked()
void MainWindow::on_stopButton_clicked()
void MainWindow::on_nextButton_clicked()
void MainWindow::on_startButton_clicked()
The startButton controls starting and stopping of playback, it is actually functions as a toggle.
void MainWindow::dragEnterEvent(QDragEnterEvent *event)
void MainWindow::dropEvent(QDropEvent *event)
void MainWindow::dbus_action(const QString &msg)
void MainWindow::randomImage()
void MainWindow::time_updater()
void MainWindow::desktopNotify(QString qimage)
void MainWindow::soundNotify()
void MainWindow::on_timerSlider_valueChanged(int value)
void MainWindow::livearth()
void MainWindow::stop_livearth()
void MainWindow::add_new_album()
void MainWindow::start_livearth_extras_concurrent_thread()
void MainWindow::livearth_extras()
void MainWindow::handle()
void MainWindow::httpFinished()
bool MainWindow::changeBackground(QString picture)
void MainWindow::minimized()
Referenced by changeEvent, MainWindow.
void MainWindow::clickSysTrayIcon(QSystemTrayIcon::ActivationReason reason)
References Ui_MainWindow::nextButton, pref.
Referenced by MainWindow.
void MainWindow::ShowPreferences()
References pref.
Referenced by MainWindow.
void MainWindow::ShowExtras()
References extras_shown.
Referenced by MainWindow.
void MainWindow::menushowabout()
Referenced by MainWindow.
void MainWindow::showClicked()
Referenced by MainWindow.
void MainWindow::pruneList()
References Ui_MainWindow::listWidget.
Referenced by MainWindow.
void MainWindow::removeDisk()
References Ui_MainWindow::listWidget.
void MainWindow::load()
References Ui_MainWindow::action_Load, Ui_MainWindow::label_9, Ui_MainWindow::listWidget.
Referenced by MainWindow.
void MainWindow::showProperties()
References Ui_MainWindow::listWidget.
Referenced by MainWindow.
void MainWindow::Openfolder()
References Ui_MainWindow::listWidget.
void MainWindow::copyImage()
References Ui_MainWindow::listWidget.
void MainWindow::copyPath()
References Ui_MainWindow::listWidget.
void MainWindow::errorstopprocess()
void MainWindow::close_minimize()
References minimize_to_tray.
Referenced by MainWindow.
void MainWindow::save_album()
References Ui_MainWindow::listWidget.
Referenced by MainWindow.