Ui_MainWindow
QAction* Ui_MainWindow::action_Preferences
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::action_About
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionQuit_Ctrl_Q
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::action_Start
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionS_top
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::action_Pause
Referenced by retranslateUi, setupUi.
QAction* Ui_MainWindow::action_Next_Image
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionRemove_list
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::action_Load
Referenced by MainWindow::load, MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionAdd_single_images
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionAdd_Folder
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionAdd_a_Wallch_album
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionHistory
Referenced by retranslateUi, setupUi.
QAction* Ui_MainWindow::action_Previous_Image_Shift_Ctrl_B
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::actionExtras
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QAction* Ui_MainWindow::save_as
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QWidget* Ui_MainWindow::centralWidget
Referenced by setupUi.
QListWidget* Ui_MainWindow::listWidget
Referenced by MainWindow::copyImage, MainWindow::copyPath, MainWindow::load, MainWindow::MainWindow, MainWindow::Openfolder, MainWindow::pruneList, MainWindow::removeDisk, MainWindow::save_album, setupUi, MainWindow::showProperties.
QLabel* Ui_MainWindow::label_5
Referenced by retranslateUi, setupUi.
QLabel* Ui_MainWindow::label_6
Referenced by retranslateUi, setupUi.
QLabel* Ui_MainWindow::label_7
Referenced by retranslateUi, setupUi.
QLabel* Ui_MainWindow::label_8
Referenced by retranslateUi, setupUi.
QLabel* Ui_MainWindow::label
Referenced by retranslateUi, setupUi.
QLabel* Ui_MainWindow::label_9
Referenced by MainWindow::load, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::addfolder
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::addButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::removeallButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::removeButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QProgressBar* Ui_MainWindow::time_for_next
Referenced by retranslateUi, setupUi.
QWidget* Ui_MainWindow::layoutWidget
Referenced by setupUi.
QGridLayout* Ui_MainWindow::gridLayout
Referenced by setupUi.
QLabel* Ui_MainWindow::label_2
Referenced by retranslateUi, setupUi.
QSlider* Ui_MainWindow::timerSlider
Referenced by MainWindow::MainWindow, setupUi.
QLabel* Ui_MainWindow::label_10
Referenced by setupUi.
QPushButton* Ui_MainWindow::previousButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::nextButton
Referenced by MainWindow::clickSysTrayIcon, MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::startButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QPushButton* Ui_MainWindow::stopButton
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QMenuBar* Ui_MainWindow::menuBar
Referenced by setupUi.
QMenu* Ui_MainWindow::menu_File
Referenced by retranslateUi, setupUi.
QMenu* Ui_MainWindow::menuAdd_Files
Referenced by MainWindow::MainWindow, retranslateUi, setupUi.
QMenu* Ui_MainWindow::menu_Edit
Referenced by retranslateUi, setupUi.
QMenu* Ui_MainWindow::menuHelp
Referenced by retranslateUi, setupUi.
QStatusBar* Ui_MainWindow::statusBar
Referenced by setupUi.
void Ui_MainWindow::setupUi(QMainWindow *MainWindow)
References action_About, action_Load, action_Next_Image, action_Pause, action_Preferences, action_Previous_Image_Shift_Ctrl_B, action_Start, actionAdd_a_Wallch_album, actionAdd_Folder, actionAdd_single_images, actionExtras, actionHistory, actionQuit_Ctrl_Q, actionRemove_list, actionS_top, addButton, addfolder, centralWidget, gridLayout, label, label_10, label_2, label_5, label_6, label_7, label_8, label_9, layoutWidget, listWidget, menu_Edit, menu_File, menuAdd_Files, menuBar, menuHelp, nextButton, previousButton, removeallButton, removeButton, retranslateUi, save_as, startButton, statusBar, stopButton, time_for_next, timerSlider.
Referenced by MainWindow::MainWindow.
void Ui_MainWindow::retranslateUi(QMainWindow *MainWindow)
References action_About, action_Load, action_Next_Image, action_Pause, action_Preferences, action_Previous_Image_Shift_Ctrl_B, action_Start, actionAdd_a_Wallch_album, actionAdd_Folder, actionAdd_single_images, actionExtras, actionHistory, actionQuit_Ctrl_Q, actionRemove_list, actionS_top, addButton, addfolder, label, label_2, label_5, label_6, label_7, label_8, label_9, menu_Edit, menu_File, menuAdd_Files, menuHelp, nextButton, previousButton, removeallButton, removeButton, save_as, startButton, stopButton, time_for_next.
Referenced by MainWindow::changeEvent, setupUi.